---

- name: Install pivproxy
  package:
    name: "{{ privoxy_packages }}"
    state: present

- name: Enable service
  service:
    name: "{{ privoxy_service }}"
    state: started
    enabled: yes
