---

- name: Install pivproxy
  package:
    name: "{{ privoxy_packages }}"
    state: present

- name: Enable service
  service:
    name: "{{ privoxy_service }}"
    state: started
    enabled: yes

- name: Open firewall port
  include_role:
    name: firewall
  vars:
    firewall_ports:
      - port: "{{ privoxy_port }}"
        proto: 'tcp' 
