---

- name: Install pivproxy
  package:
    name: "{{ privoxy_packages }}"
    state: present

- name: Enable service
  service:
    name: "{{ privoxy_service }}"
    state: started
    enabled: yes

- name: Configure privoxy
  template:
    src: templates/config.j2
    dest: /etc/privoxy/config
    mode: "0644"
  notify: Restart privoxy service

- name: Open firewall port
  include_role:
    name: firewall
  vars:
    firewall_ports:
      - port: "{{ privoxy_port }}"
        proto: "tcp"
