---

- name: Install pivproxy
  package:
    name: "{{ privoxy_packages }}"
    state: present

- name: Enable service
  service:
    name: "{{ privoxy_service }}"
    state: started
    enabled: yes

- name: Configure privoxy
  replace:
    path: /etc/privoxy/config
    regexp: "^(#)*{{ item.key }}(\s*).*"
    replace: "{{ item.key }} {{ item.value }}"
  loop: "{{ privoxy_settings | dict2items }}"

- name: Open firewall port
  include_role:
    name: firewall
  vars:
    firewall_ports:
      - port: "{{ privoxy_port }}"
        proto: 'tcp' 
